### ISSUE TITLE
Filtering doesn't work

### ISSUE THREAD

**Issue by Petemir** [kdheepak/taskwarrior-tui#320]
**Describe the bug**

Well, I know that this bug report may be a bit broad, but so far I can only define it as "filtering doesn't work". Being that broad, I am a bit surprised that no one else had reported it previously, so I thought it could be a problem of my files, so I tested with the blank-slate files at [kdheepak/taskwarrior-testdata](https://github.com/kdheepak/taskwarrior-testdata/) but still got the same error.

**To Reproduce**

- [ x ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

* Change filters, or context, but task list remains the same

![Peek 2021-11-09 11-00](https://user-images.githubusercontent.com/287105/140903997-6236d741-5f59-4785-97e1-e821a64c162e.gif)

In the gif I also show (after some failed attempts) that filtering is working with the `task` command.

As this wasn't just about contexts, but filtering in general, I thought that https://github.com/kdheepak/taskwarrior-tui/pull/318 doesn't covers it and decided to create an issue. If they are the same problem, please disregard this and close :). 

**Environment (please complete the following information):**

- Operating System: Ubuntu 21.10, kernel 5.13.0-20-generic
- Installation: Github Releases (AppImage file)
- taskwarrior-tui version:  v0.14.8
- task version: 2.6.1

**Comment by kdheepak** [comment]
Thanks for opening an issue. I just discovered this last night too. I’m trying to narrow it down, and I think it has to do with some kinds of filter strings and taskwarrior 2.6.x. The might explain why many haven’t run into it yet.

**Comment by bradyt** [comment]
I think I have a similar report:

```
> mkdir /tmp/testing && export HOME=/tmp/testing
> task rc.confirmation:no calc 1 + 1
> task add foo +bar
> task add baz
> taskwarrior-tui
```

With the resulting taskwarrior-tui session open, I try to filter with `/` and `foo` or `+bar`, but it seems to have no effect on the visible list of tasks.

- OS: Debian Bullseye
- Installation: https://github.com/kdheepak/taskwarrior-tui/releases/download/v0.14.8/taskwarrior-tui-x86_64-unknown-linux-gnu.tar.gz
- taskwarrior-tui version: v0.14.8
- task version 2.6.1

**Comment by kdheepak** [comment]
I made a new release that should fix the filtering issue when using taskwarrior 2.6.1. You can try it out by using the appropriate binary from here: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.9

**Comment by Petemir** [comment]
Ok, I tried it. Now the tasks changes, but I think some issue remains with the parsing

If I have in the filter `Check status:pending` , tasks with "Check" in the title appear (expected). If I have `status:pending Check`, an empty task list appears. If I have "-WAITING" before, or after the status, it also modifies the tasks shown.

**Comment by bradyt** [comment]
With v0.14.9, I see no tasks now.

If I do `task add foo`, then both `taskwarrior-tui` and `taskwarrior-tui -r all` show zero tasks.

**Comment by bradyt** [comment]
In the following screen recording, you can see that for a list with only a task with description "foo", `taskwarrior-tui -r all` at first displays no tasks. If I press `f`, the task finally appears. If press `BACKSPACE`, it still is shown. But it is removed if I press `z`, and still removed if I press `BACKSPACE`.

[![asciicast](https://asciinema.org/a/wafyRipLQcCdDrUChCQqw7bzO.svg)](https://asciinema.org/a/wafyRipLQcCdDrUChCQqw7bzO)

**Comment by kdheepak** [comment]
@Petemir and @bradyt, can you try the latest commit on the `main` branch? Once I write a few tests for this I'll make a new release.

**Comment by bradyt** [comment]
I built on main, filter looks great now! In my opinion, the "broad issue" is addressed.

**Comment by kdheepak** [comment]
This fix is available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.14.10 and future versions.

**Comment by Petemir** [comment]
Sorry, couldn't test it until now. Seems good! The filter works, thank you very much. I think I had a crash testing other things (next paragraphs), but sadly I wasn't able to reproduce it. I'll let you know if I manage to do it again.

fyi, I don't know if there has been a regression with #231 . Previously (i.e., v0.14.6), I could have a '#' in a filter and everything would be omitted after that. It made sense, as it would be analogous to the `task` command operation (e.g., `task # nothing is useful here` and `task` would give the same output), and it was also a "quick" way to jump between some filters (i.e., when I want to have only a subset of the conditions of a more complex filter). 

Now, inputting a # works as it would always be surrended with double quotes (i.e., as part of the description of the task). I don't know if this is as expected/designed, or I should create another issue for this (if you think it is).

**Comment by kdheepak** [comment]
Ah, that is a regression of sorts. I’m not using `task <filter> export <report>` and instead I’m using `task rc.report.<report>.filter=<filter> export <report>`. This seems more reliable when dealing with single quotes, double quotes, parentheses etc in filters. 

I can manually split out everything after a `#`, and strip it out. I’ll have to think about that.
