### ISSUE TITLE
Support for unicode/cyrillic characters in a task name

### ISSUE THREAD

**Issue by tirprox** [kdheepak/taskwarrior-tui#4]
When attempting to add a task containing any russian character, code fails with

`thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)',
/rustc/<id>/src/libcore/macros/mod.rs:34:9`

Regular taskwarrior does not have this problem

**Comment by kdheepak** [comment]
Thanks for opening an issue. Can you post an example of such a task?

**Comment by tirprox** [comment]
For example, "тест" (without quotes)

**Comment by kdheepak** [comment]
I'm not able to replicate it by copy pasting the text here as a task, i.e. `task add тест`:

<img width="797" alt="Screen Shot 2020-08-05 at 1 12 14 AM" src="https://user-images.githubusercontent.com/1813121/89382849-b491c500-d6b8-11ea-94ac-2e1c7d4f6c51.png">

Can you provide more information about your operating system / environment?

**Comment by kdheepak** [comment]
Okay I'm able to replicate this now! I'll look into what is going on. The issue only occurs if you add the task through the "add task action" in taskwarrior-tui and not through `task` the command line. I think I'll be able to fix this.

**Comment by tirprox** [comment]
I use Mint 20 Cinnamon, installed taskwarrior-tui through cargo install.
In fact, this issue appears while typing the task name, precisely on a second cyrillic character. In a task named тест, the program will break on a 'e' character. Two consecutive cyrillic characters are required.

**Comment by kdheepak** [comment]
Thanks for the report! I think I fixed that issue but it seems like removing a character when using `backspace` now fails. The issue was that I'm counting the characters and inserting the character in the appropriate location (so that you can use left and right arrow keys to insert anywhere in the string) and I was using `String::len` and that returns the incorrect length for my purposes.

**Comment by kdheepak** [comment]
This is fixed now! You can try it using `cargo install`. I've also tagged a new release, so binaries for all platforms should be available on the latest github releases shortly. Let me know if anything else comes up!

**Comment by RauchF** [comment]
I'm still experiencing this issue (albeit not with Cyrillic characters) after a fresh compile with `cargo install`.
Typing the word "Maßnahmen" taskwarrior-tui crashes upon typing the first character after `ß`:

`thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /builddir/build/BUILD/rustc-1.47.0-src/library/alloc/src/string.rs:1291:9 `

**Comment by kdheepak** [comment]
I'm not experiencing this issue when I copy the text from github and try to paste it.

<img width="600" alt="Screen Shot 2020-11-09 at 5 55 40 AM" src="https://user-images.githubusercontent.com/1813121/98543791-35c89d00-2250-11eb-97c8-b879491db34a.png">

How do I enter that grapheme from a keyboard? If you give me exact instructions and if I can replicate it I'll be able to possibly resolve it.

**Comment by kdheepak** [comment]
My initial thought is also that this could have to do with your terminal settings. `taskwarrior-tui` assumes everything is utf-8 at the moment. If your terminal is configured to use a different encoding or keyboard input is a different encoding, things are not going to work correctly. 

I would like for this to offer proper unicode support, and at the very least have instructions for how to configure the terminal so that it works when it is set to utf-8.

**Comment by kdheepak** [comment]
This is where it is possibly failing:

https://github.com/kkawakam/rustyline/blob/e9a5ccdc4f24c4a73053e6cf8897c186da5981da/src/line_buffer.rs#L225-L246

I don't see a `self.is_char_boundary(idx)` anywhere though. If you are able to compile `taskwarrior-tui` from source that would be awesome. Or, alternatively if you are able to produce instructions so that I can reproduce this that would be great.

**Comment by RauchF** [comment]
I'm using Konsole 20.08.1 as terminal emulator, set to UTF-8 as default encoding, with bash as my shell. My system locale is `en_US.UTF-8`, my input keymap is US International.

If you're using Xorg, you might be able to input the grapheme by pressing `CTRL+SHIFT+u` followed by the hex digits `DF`. On Windows it would be by entering `DF` while holding `ALT`. Not sure what the correct way would be on macOS.

I'll try checking out the source and compiling it from there, currently I am running a build made with `cargo install`. Thank you for your help so far!

**Comment by RauchF** [comment]
Okay, so a fresh build from the checked out sources here seems to not crash, it only has a small issue of the cursor jumping one column too far ahead of the input with each multibyte character entered:

![image](https://user-images.githubusercontent.com/7746494/98545781-43a11100-2296-11eb-8bb9-a7b79d6df2e8.png)

That's cosmetical though. I'll try how it behaves with a release build now, and update accordingly

**Comment by RauchF** [comment]
Okay, so a release build also seems stable - it only seems to occur with the build I did earlier today via `cargo install`. Not sure how to proceed from here.

**Comment by RauchF** [comment]
Okay, looking more closely at the output of `cargo install`, I realized what the issue was:
![image](https://user-images.githubusercontent.com/7746494/98546827-9202df80-2297-11eb-9383-f226e61e783a.png)

I can see on this repo's page that the current version is `0.9.3` - checking on crates.io the latest release there seems to be `0.5.3` though.

**Comment by kdheepak** [comment]
Ah, `cargo install` installs a very old version, since one of the dependencies is not tagged yet, so I haven't been able to push to the crates.io. I'll remove that from the instructions until that is sorted.

**Comment by kdheepak** [comment]
Perhaps we should open a new issue about the spacing. Would you like to do that? I'll close this one.

**Comment by RauchF** [comment]
Ah okay :+1: Then feel free to re-close this issue, and sorry for the confusion - glad to see this *is* fixed already.

I'll go ahead and open a new issue about the spacing. Thank you!
