### ISSUE TITLE
project / tag completion empty

### ISSUE THREAD

**Issue by xarthurx** [kdheepak/taskwarrior-tui#400]
**Describe the bug**

update `taskwarrior-tui` to the latest.
When adding new tasks, auto-completion list of *project* and *+(tag)* is empty.

![image](https://user-images.githubusercontent.com/1921878/153371719-e2c3d11e-e777-42ca-ae6b-62887dc8957c.png)

**Comment by kdheepak** [comment]
It appears to be working for me:

<img width="300" alt="Screen Shot 2022-02-10 at 3 51 06 AM" src="https://user-images.githubusercontent.com/1813121/153392053-18dad145-b29f-4a79-b881-cd68e0c36d91.png">

can you try to copy paste the content of the terminal here? I'm wondering if the foreground text and background color are the same for some reason.

**Comment by xarthurx** [comment]
> It appears to be working for me:
> 
> <img alt="Screen Shot 2022-02-10 at 3 51 06 AM" width="300" src="https://user-images.githubusercontent.com/1813121/153392053-18dad145-b29f-4a79-b881-cd68e0c36d91.png">
> 
> Can you try to copy paste the content of the terminal here? I'm wondering if the foreground text and background color are the same for some reason.

the content of the terminal? Do you mean a screenshot of my tasks? 
I think it is a color issue, as I can use `tab` to navigate and select different options.

**Comment by kdheepak** [comment]
If it is a color issue, you can probably set 

```
uda.taskwarrior-tui.style.report.completion-pane=red on black
uda.taskwarrior-tui.style.report.completion-pane-highlight=bold blue on black
```

in your `.taskrc` and see if that helps? If you share your `.taskrc` / whatever colorscheme you are using maybe I can fix it by default.

**Comment by xarthurx** [comment]
With your help, it works:
![image](https://user-images.githubusercontent.com/1921878/153929832-d56e231c-54cf-4c9b-b473-6ea9c4c9af37.png)


My original setting is:
![image](https://user-images.githubusercontent.com/1921878/153929917-db37befa-4c9e-4a3a-8f09-27bd98343041.png)

However, without your fix, it seems changing color scheme does not affect the issue.

**Comment by bradyt** [comment]
I tried this with an empty `.taskrc` with taskwarrior-tui 0.19.1, in a terminal with dark background, and it worked fine.

**Comment by bradyt** [comment]
Screenshot:

![Screen Shot 2022-02-14 at 11 12 35 AM](https://user-images.githubusercontent.com/6107051/153930472-bc997e47-b4de-4004-90bd-d7c4fd4a6606.png)

**Comment by xarthurx** [comment]
> I tried this with an empty `.taskrc` with taskwarrior-tui 0.19.1, in a terminal with dark background, and it worked fine.
> 
> However, I do recall seeing this in the past, so I'm wondering if something was fixed recently.

I tried an empty `.taskrc`, it is not working. 
I guess it may also be related to the fact I'm using Windows Terminal on windows.
But before it has no problem, so something must have been changed during the recent updates within a month.

**Comment by bradyt** [comment]
Did a git bisect, I think the visibility for me improved at commit 12b61f546910f54f03d80c58bf94582546c860ff, which is in between taskwarrior-tui tags v0.18.5 and v0.19.0.

**Comment by kdheepak** [comment]
Thanks for digging into that!

It looks like I removed the default foreground color as black in that commit: 

https://github.com/kdheepak/taskwarrior-tui/commit/12b61f546910f54f03d80c58bf94582546c860ff#diff-0b979b6de560b29c1d97336878db56179224aa21d96fe099630c6628479ed020L891

**Comment by kdheepak** [comment]
@xarthurx and @bradyt can you try again with the PR? I added a default foreground of `Black` in the PR. 

Also @bradyt can you describe in what way visibility improved for you? It seems identical for me:

![Screen Shot 2022-02-14 at 1 17 56 PM](https://user-images.githubusercontent.com/1813121/153939983-92ce5dcf-86b5-458b-a06c-0f9f90ab6f1b.png)
![Screen Shot 2022-02-14 at 1 18 51 PM](https://user-images.githubusercontent.com/1813121/153939987-e487bebd-1a5d-4309-9277-12d8c47764cb.png)
.

**Comment by kdheepak** [comment]
I'm going to merge the PR and make a new release because I'm pretty sure this will resolve it and I won't have time to do it later :)

**Comment by kdheepak** [comment]
Yeah, finding / making colorschemes that have nice contrast in just 16 colors is a real challenge. It would nice to have some standard about what colors make sense for what purpose in a terminal (e.g. borders, text foreground, text background etc). For `taskwarrior-tui` I want to side step dealing with that and just make all colors configurable.

**Comment by kdheepak** [comment]
This should be resolved in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.2.

**Comment by bradyt** [comment]
I haven't check Windows Terminal, but I can still see completion candidates in Terminal.app with dark background with your new code.

**Comment by xarthurx** [comment]
It still not working for me in Windows Terminal.
What's worse, the fix here now make the completion dialog totally black, I cannot see the test either...

> If it is a color issue, you can probably set
> 
> ```
> uda.taskwarrior-tui.style.report.completion-pane=red on black
> uda.taskwarrior-tui.style.report.completion-pane-highlight=bold blue on black
> ```
> 
> in your `.taskrc` and see if that helps? If you share your `.taskrc` / whatever colorscheme you are using maybe I can fix it by default.

**Comment by kdheepak** [comment]
> What's worse, the fix here now make the completion dialog totally black, I cannot see the test either...

Can you clarify what you mean by “cannot see the test”? Do you mean when you set the colors in the `.taskrc` it doesn’t work?

**Comment by kdheepak** [comment]
I made another change to the `main` branch that should hopefully fix this. Can you try that?

**Comment by kdheepak** [comment]
You can try the precompiled release here: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.19.3

**Comment by xarthurx** [comment]
@kdheepak  Both (w/o your fix in `.taskrc`) work now. Wonderful!

**Comment by kdheepak** [comment]
Great!
