### ISSUE TITLE
Priority colors not taken into account

### ISSUE THREAD

**Issue by b1two** [kdheepak/taskwarrior-tui#99]
**Describe the bug**

The tasks displayed in taskwarrior-tui do not get colored correctly when they have been assigned a priority.
When using task the colors are correctly displayed.

**To Reproduce**

`.taskrc`:
```
data.location=/tmp/test/.task
uda.priority.values=U,H,M,L
color.uda.priority.U=red
color.uda.priority.H=green
```
`.task/pending.data`:
```
[description:"my task" entry:"1613297205" modified:"1613300150" priority:"H" status:"pending" uuid:"69104b6b-0d21-4db0-9616-b62cf3060524"]
[description:"my other task" entry:"1613300157" modified:"1613300494" priority:"U" status:"pending" uuid:"2ddc51f0-bc3b-452e-a49a-b69d7f7af351"]
[description:"my other other task" entry:"1613300398" modified:"1613300490" status:"pending" uuid:"274c042f-7ea9-4051-bd3c-9d6e801defd3"]
```
task output:
![taskwarrior-tui_colors-1613300518](https://user-images.githubusercontent.com/43686727/107874861-dd431480-6ebc-11eb-9225-2fcba4e11987.png)
taskwarrior-tui:
![taskwarrior-tui_colors-1613300501](https://user-images.githubusercontent.com/43686727/107874867-ea600380-6ebc-11eb-97f9-5495db609038.png)

**Environment (please complete the following information):**

- Operating System: Debian 10
- Installation: From source
- taskwarrior-tui version: HEAD at commit b0faf774fdf8adcb70f674c5145c6181d3b2da19
- task version:

```bash
% task --version
2.5.3
```

**Additional context and information**

Maybe linked to #68.
Feel free to ask for any missing information.

**Comment by kdheepak** [comment]
Thanks for opening this issue! It should be resolved in the next release!

**Comment by kdheepak** [comment]
This is available in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.10.0

**Comment by b1two** [comment]
Thanks, just tried it, seems that there is still an issue regarding tasks with priority and project set.
With the following `pending.task`:
```
[description:"mytask" entry:"1605107671" modified:"1613322969" priority:"H" project:"myproject" status:"pending" uuid:"bb236e33-8dce-48eb-83c6-18b700aeff58"]
```
And the following `.taskrc`:
```
data.location=/tmp/test/.task
uda.priority.values=U,H,M,L
color.uda.priority.U=red
color.uda.priority.H=green
```
The task is still not colored whereas only the priority is associated with a color (not the project). It looks like taskwarrior-tui is always taking the project color even when no color is set, and therefore uses the default one; while task uses the priority color if none is specified for the project.

The behavior regarding simple tasks works fine though, thanks for the fix :)

**Comment by kdheepak** [comment]
You are right! The way all the colors interact is complex in taskwarrior, and I'm still figuring it all out. This will probably take a few iterations to get it all working :)

**Comment by kdheepak** [comment]
@b1two do you have specific colors for each project? Can you share the part of your `.taskrc` that sets the colors for the projects?

**Comment by kdheepak** [comment]
```
uda.priority.values=U,H,M,L
urgency.uda.priority.U.coefficient=15.0
color.uda.priority.U=red
color.uda.priority.L=blue
color.uda.priority.M=yellow
color.uda.priority.H=green
color.project.wth=green on black
color.tagged=red on blue
```

I named a project `wth` and tagged other tasks. I'm fairly confident about this working as intended now. This is the screenshot of what taskwarrior-tui looks like and what taskwarrior looks like:

![Screen Shot 2021-02-14 at 7 03 26 PM](https://user-images.githubusercontent.com/1813121/107897801-53646d00-6ef7-11eb-90fa-2918811d7d32.png)

I think there might still be a couple of corner cases with `due` tasks. But I'll have to iron those out later.
